name: helper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  splashscreen: ^1.2.0
  fluttertoast: ^6.0.1
  english_words: ^3.1.5
  backdrop: ^0.4.1
  animations: ^1.1.1
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios : true
  image_path : "assets/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - lib/images/giphy (1).gif
     - lib/images/giphy2.gif
     - lib/Textfile/1file.txt
     - lib/Textfile/2file.txt
     - lib/Textfile/3file.txt
     - lib/Textfile/4file.txt
     - lib/Textfile/5file.txt
     - lib/Textfile/6file.txt
     - lib/Textfile/7file.txt
     - lib/Textfile/8file.txt
     - lib/Textfile/9file.txt
     - lib/images/download (1).png
     - lib/Textfile/10file.txt
     - lib/Textfile/11file.txt
     - lib/Textfile/12file.txt
     - lib/Textfile/13file.txt
     - lib/Textfile/14file.txt
     - lib/Textfile/15file.txt
     - lib/Textfile/16file.txt
     - lib/Textfile/17file.txt
     - lib/Textfile/18file.txt
     - lib/Textfile/19file.txt
     - lib/Textfile/20file.txt
     - lib/Textfile/21file.txt
     - lib/Textfile/22file.txt
     - lib/Textfile/23file.txt
     - lib/Textfile/24file.txt
     - lib/Textfile/25file.txt
     - lib/Textfile/26file.txt
     - lib/Textfile/27file.txt
     - lib/Textfile/28file.txt
     - lib/Textfile/29file.txt
     - lib/Textfile/30file.txt
     - lib/Textfile/31file.txt
     - lib/Textfile/32file.txt
     - lib/Textfile/33file.txt
     - lib/Textfile/34file.txt
     - lib/Textfile/35file.txt
     - lib/Textfile/36file.txt
     - lib/Textfile/37file.txt
     - lib/Textfile/38file.txt
     - lib/Textfile/39file.txt
     - lib/Textfile/40file.txt
     - lib/images/ij.jpg



         # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
